//go:build darwin

#ifndef _events_h
#define _events_h

extern void processApplicationEvent(unsigned int, void* data);
extern void processWindowEvent(unsigned int, unsigned int);

#define EventApplicationDidBecomeActive 1058
#define EventApplicationDidChangeBackingProperties 1059
#define EventApplicationDidChangeEffectiveAppearance 1060
#define EventApplicationDidChangeIcon 1061
#define EventApplicationDidChangeOcclusionState 1062
#define EventApplicationDidChangeScreenParameters 1063
#define EventApplicationDidChangeStatusBarFrame 1064
#define EventApplicationDidChangeStatusBarOrientation 1065
#define EventApplicationDidChangeTheme 1066
#define EventApplicationDidFinishLaunching 1067
#define EventApplicationDidHide 1068
#define EventApplicationDidResignActive 1069
#define EventApplicationDidUnhide 1070
#define EventApplicationDidUpdate 1071
#define EventApplicationShouldHandleReopen 1072
#define EventApplicationWillBecomeActive 1073
#define EventApplicationWillFinishLaunching 1074
#define EventApplicationWillHide 1075
#define EventApplicationWillResignActive 1076
#define EventApplicationWillTerminate 1077
#define EventApplicationWillUnhide 1078
#define EventApplicationWillUpdate 1079
#define EventMenuDidAddItem 1080
#define EventMenuDidBeginTracking 1081
#define EventMenuDidClose 1082
#define EventMenuDidDisplayItem 1083
#define EventMenuDidEndTracking 1084
#define EventMenuDidHighlightItem 1085
#define EventMenuDidOpen 1086
#define EventMenuDidPopUp 1087
#define EventMenuDidRemoveItem 1088
#define EventMenuDidSendAction 1089
#define EventMenuDidSendActionToItem 1090
#define EventMenuDidUpdate 1091
#define EventMenuWillAddItem 1092
#define EventMenuWillBeginTracking 1093
#define EventMenuWillDisplayItem 1094
#define EventMenuWillEndTracking 1095
#define EventMenuWillHighlightItem 1096
#define EventMenuWillOpen 1097
#define EventMenuWillPopUp 1098
#define EventMenuWillRemoveItem 1099
#define EventMenuWillSendAction 1100
#define EventMenuWillSendActionToItem 1101
#define EventMenuWillUpdate 1102
#define EventWebViewDidCommitNavigation 1103
#define EventWebViewDidFinishNavigation 1104
#define EventWebViewDidReceiveServerRedirectForProvisionalNavigation 1105
#define EventWebViewDidStartProvisionalNavigation 1106
#define EventWindowDidBecomeKey 1107
#define EventWindowDidBecomeMain 1108
#define EventWindowDidBeginSheet 1109
#define EventWindowDidChangeAlpha 1110
#define EventWindowDidChangeBackingLocation 1111
#define EventWindowDidChangeBackingProperties 1112
#define EventWindowDidChangeCollectionBehavior 1113
#define EventWindowDidChangeEffectiveAppearance 1114
#define EventWindowDidChangeOcclusionState 1115
#define EventWindowDidChangeOrderingMode 1116
#define EventWindowDidChangeScreen 1117
#define EventWindowDidChangeScreenParameters 1118
#define EventWindowDidChangeScreenProfile 1119
#define EventWindowDidChangeScreenSpace 1120
#define EventWindowDidChangeScreenSpaceProperties 1121
#define EventWindowDidChangeSharingType 1122
#define EventWindowDidChangeSpace 1123
#define EventWindowDidChangeSpaceOrderingMode 1124
#define EventWindowDidChangeTitle 1125
#define EventWindowDidChangeToolbar 1126
#define EventWindowDidDeminiaturize 1127
#define EventWindowDidEndSheet 1128
#define EventWindowDidEnterFullScreen 1129
#define EventWindowDidEnterVersionBrowser 1130
#define EventWindowDidExitFullScreen 1131
#define EventWindowDidExitVersionBrowser 1132
#define EventWindowDidExpose 1133
#define EventWindowDidFocus 1134
#define EventWindowDidMiniaturize 1135
#define EventWindowDidMove 1136
#define EventWindowDidOrderOffScreen 1137
#define EventWindowDidOrderOnScreen 1138
#define EventWindowDidResignKey 1139
#define EventWindowDidResignMain 1140
#define EventWindowDidResize 1141
#define EventWindowDidUpdate 1142
#define EventWindowDidUpdateAlpha 1143
#define EventWindowDidUpdateCollectionBehavior 1144
#define EventWindowDidUpdateCollectionProperties 1145
#define EventWindowDidUpdateShadow 1146
#define EventWindowDidUpdateTitle 1147
#define EventWindowDidUpdateToolbar 1148
#define EventWindowDidZoom 1149
#define EventWindowFileDraggingEntered 1150
#define EventWindowFileDraggingExited 1151
#define EventWindowFileDraggingPerformed 1152
#define EventWindowHide 1153
#define EventWindowMaximise 1154
#define EventWindowUnMaximise 1155
#define EventWindowMinimise 1156
#define EventWindowUnMinimise 1157
#define EventWindowShouldClose 1158
#define EventWindowShow 1159
#define EventWindowWillBecomeKey 1160
#define EventWindowWillBecomeMain 1161
#define EventWindowWillBeginSheet 1162
#define EventWindowWillChangeOrderingMode 1163
#define EventWindowWillClose 1164
#define EventWindowWillDeminiaturize 1165
#define EventWindowWillEnterFullScreen 1166
#define EventWindowWillEnterVersionBrowser 1167
#define EventWindowWillExitFullScreen 1168
#define EventWindowWillExitVersionBrowser 1169
#define EventWindowWillFocus 1170
#define EventWindowWillMiniaturize 1171
#define EventWindowWillMove 1172
#define EventWindowWillOrderOffScreen 1173
#define EventWindowWillOrderOnScreen 1174
#define EventWindowWillResignMain 1175
#define EventWindowWillResize 1176
#define EventWindowWillUnfocus 1177
#define EventWindowWillUpdate 1178
#define EventWindowWillUpdateAlpha 1179
#define EventWindowWillUpdateCollectionBehavior 1180
#define EventWindowWillUpdateCollectionProperties 1181
#define EventWindowWillUpdateShadow 1182
#define EventWindowWillUpdateTitle 1183
#define EventWindowWillUpdateToolbar 1184
#define EventWindowWillUpdateVisibility 1185
#define EventWindowWillUseStandardFrame 1186
#define EventWindowZoomIn 1187
#define EventWindowZoomOut 1188
#define EventWindowZoomReset 1189

#define MAX_EVENTS 1190


#endif