package events

type ApplicationEventType uint
type WindowEventType      uint

var Common = newCommonEvents()

type commonEvents struct {
	ApplicationOpenedWithFile ApplicationEventType
	ApplicationStarted ApplicationEventType
	ApplicationLaunchedWithUrl ApplicationEventType
	ThemeChanged ApplicationEventType
	WindowClosing WindowEventType
	WindowDidMove WindowEventType
	WindowDidResize WindowEventType
	WindowDPIChanged WindowEventType
	WindowFilesDropped WindowEventType
	WindowFocus WindowEventType
	WindowFullscreen WindowEventType
	WindowHide WindowEventType
	WindowLostFocus WindowEventType
	WindowMaximise WindowEventType
	WindowMinimise WindowEventType
	WindowToggleFrameless WindowEventType
	WindowRestore WindowEventType
	WindowRuntimeReady WindowEventType
	WindowShow WindowEventType
	WindowUnFullscreen WindowEventType
	WindowUnMaximise WindowEventType
	WindowUnMinimise WindowEventType
	WindowZoom WindowEventType
	WindowZoomIn WindowEventType
	WindowZoomOut WindowEventType
	WindowZoomReset WindowEventType
}

func newCommonEvents() commonEvents {
	return commonEvents{
		ApplicationOpenedWithFile: 1024,
		ApplicationStarted: 1025,
		ApplicationLaunchedWithUrl: 1026,
		ThemeChanged: 1027,
		WindowClosing: 1028,
		WindowDidMove: 1029,
		WindowDidResize: 1030,
		WindowDPIChanged: 1031,
		WindowFilesDropped: 1032,
		WindowFocus: 1033,
		WindowFullscreen: 1034,
		WindowHide: 1035,
		WindowLostFocus: 1036,
		WindowMaximise: 1037,
		WindowMinimise: 1038,
		WindowToggleFrameless: 1039,
		WindowRestore: 1040,
		WindowRuntimeReady: 1041,
		WindowShow: 1042,
		WindowUnFullscreen: 1043,
		WindowUnMaximise: 1044,
		WindowUnMinimise: 1045,
		WindowZoom: 1046,
		WindowZoomIn: 1047,
		WindowZoomOut: 1048,
		WindowZoomReset: 1049,
	}
}

var Linux = newLinuxEvents()

type linuxEvents struct {
	ApplicationStartup ApplicationEventType
	SystemThemeChanged ApplicationEventType
	WindowDeleteEvent WindowEventType
	WindowDidMove WindowEventType
	WindowDidResize WindowEventType
	WindowFocusIn WindowEventType
	WindowFocusOut WindowEventType
	WindowLoadChanged WindowEventType
}

func newLinuxEvents() linuxEvents {
	return linuxEvents{
		ApplicationStartup: 1050,
		SystemThemeChanged: 1051,
		WindowDeleteEvent: 1052,
		WindowDidMove: 1053,
		WindowDidResize: 1054,
		WindowFocusIn: 1055,
		WindowFocusOut: 1056,
		WindowLoadChanged: 1057,
	}
}

var Mac = newMacEvents()

type macEvents struct {
	ApplicationDidBecomeActive ApplicationEventType
	ApplicationDidChangeBackingProperties ApplicationEventType
	ApplicationDidChangeEffectiveAppearance ApplicationEventType
	ApplicationDidChangeIcon ApplicationEventType
	ApplicationDidChangeOcclusionState ApplicationEventType
	ApplicationDidChangeScreenParameters ApplicationEventType
	ApplicationDidChangeStatusBarFrame ApplicationEventType
	ApplicationDidChangeStatusBarOrientation ApplicationEventType
	ApplicationDidChangeTheme ApplicationEventType
	ApplicationDidFinishLaunching ApplicationEventType
	ApplicationDidHide ApplicationEventType
	ApplicationDidResignActive ApplicationEventType
	ApplicationDidUnhide ApplicationEventType
	ApplicationDidUpdate ApplicationEventType
	ApplicationShouldHandleReopen ApplicationEventType
	ApplicationWillBecomeActive ApplicationEventType
	ApplicationWillFinishLaunching ApplicationEventType
	ApplicationWillHide ApplicationEventType
	ApplicationWillResignActive ApplicationEventType
	ApplicationWillTerminate ApplicationEventType
	ApplicationWillUnhide ApplicationEventType
	ApplicationWillUpdate ApplicationEventType
	MenuDidAddItem ApplicationEventType
	MenuDidBeginTracking ApplicationEventType
	MenuDidClose ApplicationEventType
	MenuDidDisplayItem ApplicationEventType
	MenuDidEndTracking ApplicationEventType
	MenuDidHighlightItem ApplicationEventType
	MenuDidOpen ApplicationEventType
	MenuDidPopUp ApplicationEventType
	MenuDidRemoveItem ApplicationEventType
	MenuDidSendAction ApplicationEventType
	MenuDidSendActionToItem ApplicationEventType
	MenuDidUpdate ApplicationEventType
	MenuWillAddItem ApplicationEventType
	MenuWillBeginTracking ApplicationEventType
	MenuWillDisplayItem ApplicationEventType
	MenuWillEndTracking ApplicationEventType
	MenuWillHighlightItem ApplicationEventType
	MenuWillOpen ApplicationEventType
	MenuWillPopUp ApplicationEventType
	MenuWillRemoveItem ApplicationEventType
	MenuWillSendAction ApplicationEventType
	MenuWillSendActionToItem ApplicationEventType
	MenuWillUpdate ApplicationEventType
	WebViewDidCommitNavigation WindowEventType
	WebViewDidFinishNavigation WindowEventType
	WebViewDidReceiveServerRedirectForProvisionalNavigation WindowEventType
	WebViewDidStartProvisionalNavigation WindowEventType
	WindowDidBecomeKey WindowEventType
	WindowDidBecomeMain WindowEventType
	WindowDidBeginSheet WindowEventType
	WindowDidChangeAlpha WindowEventType
	WindowDidChangeBackingLocation WindowEventType
	WindowDidChangeBackingProperties WindowEventType
	WindowDidChangeCollectionBehavior WindowEventType
	WindowDidChangeEffectiveAppearance WindowEventType
	WindowDidChangeOcclusionState WindowEventType
	WindowDidChangeOrderingMode WindowEventType
	WindowDidChangeScreen WindowEventType
	WindowDidChangeScreenParameters WindowEventType
	WindowDidChangeScreenProfile WindowEventType
	WindowDidChangeScreenSpace WindowEventType
	WindowDidChangeScreenSpaceProperties WindowEventType
	WindowDidChangeSharingType WindowEventType
	WindowDidChangeSpace WindowEventType
	WindowDidChangeSpaceOrderingMode WindowEventType
	WindowDidChangeTitle WindowEventType
	WindowDidChangeToolbar WindowEventType
	WindowDidDeminiaturize WindowEventType
	WindowDidEndSheet WindowEventType
	WindowDidEnterFullScreen WindowEventType
	WindowDidEnterVersionBrowser WindowEventType
	WindowDidExitFullScreen WindowEventType
	WindowDidExitVersionBrowser WindowEventType
	WindowDidExpose WindowEventType
	WindowDidFocus WindowEventType
	WindowDidMiniaturize WindowEventType
	WindowDidMove WindowEventType
	WindowDidOrderOffScreen WindowEventType
	WindowDidOrderOnScreen WindowEventType
	WindowDidResignKey WindowEventType
	WindowDidResignMain WindowEventType
	WindowDidResize WindowEventType
	WindowDidUpdate WindowEventType
	WindowDidUpdateAlpha WindowEventType
	WindowDidUpdateCollectionBehavior WindowEventType
	WindowDidUpdateCollectionProperties WindowEventType
	WindowDidUpdateShadow WindowEventType
	WindowDidUpdateTitle WindowEventType
	WindowDidUpdateToolbar WindowEventType
	WindowDidZoom WindowEventType
	WindowFileDraggingEntered WindowEventType
	WindowFileDraggingExited WindowEventType
	WindowFileDraggingPerformed WindowEventType
	WindowHide WindowEventType
	WindowMaximise WindowEventType
	WindowUnMaximise WindowEventType
	WindowMinimise WindowEventType
	WindowUnMinimise WindowEventType
	WindowShouldClose WindowEventType
	WindowShow WindowEventType
	WindowWillBecomeKey WindowEventType
	WindowWillBecomeMain WindowEventType
	WindowWillBeginSheet WindowEventType
	WindowWillChangeOrderingMode WindowEventType
	WindowWillClose WindowEventType
	WindowWillDeminiaturize WindowEventType
	WindowWillEnterFullScreen WindowEventType
	WindowWillEnterVersionBrowser WindowEventType
	WindowWillExitFullScreen WindowEventType
	WindowWillExitVersionBrowser WindowEventType
	WindowWillFocus WindowEventType
	WindowWillMiniaturize WindowEventType
	WindowWillMove WindowEventType
	WindowWillOrderOffScreen WindowEventType
	WindowWillOrderOnScreen WindowEventType
	WindowWillResignMain WindowEventType
	WindowWillResize WindowEventType
	WindowWillUnfocus WindowEventType
	WindowWillUpdate WindowEventType
	WindowWillUpdateAlpha WindowEventType
	WindowWillUpdateCollectionBehavior WindowEventType
	WindowWillUpdateCollectionProperties WindowEventType
	WindowWillUpdateShadow WindowEventType
	WindowWillUpdateTitle WindowEventType
	WindowWillUpdateToolbar WindowEventType
	WindowWillUpdateVisibility WindowEventType
	WindowWillUseStandardFrame WindowEventType
	WindowZoomIn WindowEventType
	WindowZoomOut WindowEventType
	WindowZoomReset WindowEventType
}

func newMacEvents() macEvents {
	return macEvents{
		ApplicationDidBecomeActive: 1058,
		ApplicationDidChangeBackingProperties: 1059,
		ApplicationDidChangeEffectiveAppearance: 1060,
		ApplicationDidChangeIcon: 1061,
		ApplicationDidChangeOcclusionState: 1062,
		ApplicationDidChangeScreenParameters: 1063,
		ApplicationDidChangeStatusBarFrame: 1064,
		ApplicationDidChangeStatusBarOrientation: 1065,
		ApplicationDidChangeTheme: 1066,
		ApplicationDidFinishLaunching: 1067,
		ApplicationDidHide: 1068,
		ApplicationDidResignActive: 1069,
		ApplicationDidUnhide: 1070,
		ApplicationDidUpdate: 1071,
		ApplicationShouldHandleReopen: 1072,
		ApplicationWillBecomeActive: 1073,
		ApplicationWillFinishLaunching: 1074,
		ApplicationWillHide: 1075,
		ApplicationWillResignActive: 1076,
		ApplicationWillTerminate: 1077,
		ApplicationWillUnhide: 1078,
		ApplicationWillUpdate: 1079,
		MenuDidAddItem: 1080,
		MenuDidBeginTracking: 1081,
		MenuDidClose: 1082,
		MenuDidDisplayItem: 1083,
		MenuDidEndTracking: 1084,
		MenuDidHighlightItem: 1085,
		MenuDidOpen: 1086,
		MenuDidPopUp: 1087,
		MenuDidRemoveItem: 1088,
		MenuDidSendAction: 1089,
		MenuDidSendActionToItem: 1090,
		MenuDidUpdate: 1091,
		MenuWillAddItem: 1092,
		MenuWillBeginTracking: 1093,
		MenuWillDisplayItem: 1094,
		MenuWillEndTracking: 1095,
		MenuWillHighlightItem: 1096,
		MenuWillOpen: 1097,
		MenuWillPopUp: 1098,
		MenuWillRemoveItem: 1099,
		MenuWillSendAction: 1100,
		MenuWillSendActionToItem: 1101,
		MenuWillUpdate: 1102,
		WebViewDidCommitNavigation: 1103,
		WebViewDidFinishNavigation: 1104,
		WebViewDidReceiveServerRedirectForProvisionalNavigation: 1105,
		WebViewDidStartProvisionalNavigation: 1106,
		WindowDidBecomeKey: 1107,
		WindowDidBecomeMain: 1108,
		WindowDidBeginSheet: 1109,
		WindowDidChangeAlpha: 1110,
		WindowDidChangeBackingLocation: 1111,
		WindowDidChangeBackingProperties: 1112,
		WindowDidChangeCollectionBehavior: 1113,
		WindowDidChangeEffectiveAppearance: 1114,
		WindowDidChangeOcclusionState: 1115,
		WindowDidChangeOrderingMode: 1116,
		WindowDidChangeScreen: 1117,
		WindowDidChangeScreenParameters: 1118,
		WindowDidChangeScreenProfile: 1119,
		WindowDidChangeScreenSpace: 1120,
		WindowDidChangeScreenSpaceProperties: 1121,
		WindowDidChangeSharingType: 1122,
		WindowDidChangeSpace: 1123,
		WindowDidChangeSpaceOrderingMode: 1124,
		WindowDidChangeTitle: 1125,
		WindowDidChangeToolbar: 1126,
		WindowDidDeminiaturize: 1127,
		WindowDidEndSheet: 1128,
		WindowDidEnterFullScreen: 1129,
		WindowDidEnterVersionBrowser: 1130,
		WindowDidExitFullScreen: 1131,
		WindowDidExitVersionBrowser: 1132,
		WindowDidExpose: 1133,
		WindowDidFocus: 1134,
		WindowDidMiniaturize: 1135,
		WindowDidMove: 1136,
		WindowDidOrderOffScreen: 1137,
		WindowDidOrderOnScreen: 1138,
		WindowDidResignKey: 1139,
		WindowDidResignMain: 1140,
		WindowDidResize: 1141,
		WindowDidUpdate: 1142,
		WindowDidUpdateAlpha: 1143,
		WindowDidUpdateCollectionBehavior: 1144,
		WindowDidUpdateCollectionProperties: 1145,
		WindowDidUpdateShadow: 1146,
		WindowDidUpdateTitle: 1147,
		WindowDidUpdateToolbar: 1148,
		WindowDidZoom: 1149,
		WindowFileDraggingEntered: 1150,
		WindowFileDraggingExited: 1151,
		WindowFileDraggingPerformed: 1152,
		WindowHide: 1153,
		WindowMaximise: 1154,
		WindowUnMaximise: 1155,
		WindowMinimise: 1156,
		WindowUnMinimise: 1157,
		WindowShouldClose: 1158,
		WindowShow: 1159,
		WindowWillBecomeKey: 1160,
		WindowWillBecomeMain: 1161,
		WindowWillBeginSheet: 1162,
		WindowWillChangeOrderingMode: 1163,
		WindowWillClose: 1164,
		WindowWillDeminiaturize: 1165,
		WindowWillEnterFullScreen: 1166,
		WindowWillEnterVersionBrowser: 1167,
		WindowWillExitFullScreen: 1168,
		WindowWillExitVersionBrowser: 1169,
		WindowWillFocus: 1170,
		WindowWillMiniaturize: 1171,
		WindowWillMove: 1172,
		WindowWillOrderOffScreen: 1173,
		WindowWillOrderOnScreen: 1174,
		WindowWillResignMain: 1175,
		WindowWillResize: 1176,
		WindowWillUnfocus: 1177,
		WindowWillUpdate: 1178,
		WindowWillUpdateAlpha: 1179,
		WindowWillUpdateCollectionBehavior: 1180,
		WindowWillUpdateCollectionProperties: 1181,
		WindowWillUpdateShadow: 1182,
		WindowWillUpdateTitle: 1183,
		WindowWillUpdateToolbar: 1184,
		WindowWillUpdateVisibility: 1185,
		WindowWillUseStandardFrame: 1186,
		WindowZoomIn: 1187,
		WindowZoomOut: 1188,
		WindowZoomReset: 1189,
	}
}

var Windows = newWindowsEvents()

type windowsEvents struct {
	APMPowerSettingChange ApplicationEventType
	APMPowerStatusChange ApplicationEventType
	APMResumeAutomatic ApplicationEventType
	APMResumeSuspend ApplicationEventType
	APMSuspend ApplicationEventType
	ApplicationStarted ApplicationEventType
	SystemThemeChanged ApplicationEventType
	WebViewNavigationCompleted WindowEventType
	WindowActive WindowEventType
	WindowBackgroundErase WindowEventType
	WindowClickActive WindowEventType
	WindowClosing WindowEventType
	WindowDidMove WindowEventType
	WindowDidResize WindowEventType
	WindowDPIChanged WindowEventType
	WindowDragDrop WindowEventType
	WindowDragEnter WindowEventType
	WindowDragLeave WindowEventType
	WindowDragOver WindowEventType
	WindowEndMove WindowEventType
	WindowEndResize WindowEventType
	WindowFullscreen WindowEventType
	WindowHide WindowEventType
	WindowInactive WindowEventType
	WindowKeyDown WindowEventType
	WindowKeyUp WindowEventType
	WindowKillFocus WindowEventType
	WindowNonClientHit WindowEventType
	WindowNonClientMouseDown WindowEventType
	WindowNonClientMouseLeave WindowEventType
	WindowNonClientMouseMove WindowEventType
	WindowNonClientMouseUp WindowEventType
	WindowPaint WindowEventType
	WindowRestore WindowEventType
	WindowSetFocus WindowEventType
	WindowShow WindowEventType
	WindowStartMove WindowEventType
	WindowStartResize WindowEventType
	WindowUnFullscreen WindowEventType
	WindowZOrderChanged WindowEventType
	WindowMinimise WindowEventType
	WindowUnMinimise WindowEventType
	WindowMaximise WindowEventType
	WindowUnMaximise WindowEventType
}

func newWindowsEvents() windowsEvents {
	return windowsEvents{
		APMPowerSettingChange: 1190,
		APMPowerStatusChange: 1191,
		APMResumeAutomatic: 1192,
		APMResumeSuspend: 1193,
		APMSuspend: 1194,
		ApplicationStarted: 1195,
		SystemThemeChanged: 1196,
		WebViewNavigationCompleted: 1197,
		WindowActive: 1198,
		WindowBackgroundErase: 1199,
		WindowClickActive: 1200,
		WindowClosing: 1201,
		WindowDidMove: 1202,
		WindowDidResize: 1203,
		WindowDPIChanged: 1204,
		WindowDragDrop: 1205,
		WindowDragEnter: 1206,
		WindowDragLeave: 1207,
		WindowDragOver: 1208,
		WindowEndMove: 1209,
		WindowEndResize: 1210,
		WindowFullscreen: 1211,
		WindowHide: 1212,
		WindowInactive: 1213,
		WindowKeyDown: 1214,
		WindowKeyUp: 1215,
		WindowKillFocus: 1216,
		WindowNonClientHit: 1217,
		WindowNonClientMouseDown: 1218,
		WindowNonClientMouseLeave: 1219,
		WindowNonClientMouseMove: 1220,
		WindowNonClientMouseUp: 1221,
		WindowPaint: 1222,
		WindowRestore: 1223,
		WindowSetFocus: 1224,
		WindowShow: 1225,
		WindowStartMove: 1226,
		WindowStartResize: 1227,
		WindowUnFullscreen: 1228,
		WindowZOrderChanged: 1229,
		WindowMinimise: 1230,
		WindowUnMinimise: 1231,
		WindowMaximise: 1232,
		WindowUnMaximise: 1233,
	}
}

func JSEvent(event uint) string {
	return eventToJS[event]
}

var eventToJS = map[uint]string{
	1024: "ApplicationOpenedWithFile",
	1025: "ApplicationStarted",
	1026: "ApplicationLaunchedWithUrl",
	1027: "ThemeChanged",
	1028: "WindowClosing",
	1029: "WindowDidMove",
	1030: "WindowDidResize",
	1031: "WindowDPIChanged",
	1032: "WindowFilesDropped",
	1033: "WindowFocus",
	1034: "WindowFullscreen",
	1035: "WindowHide",
	1036: "WindowLostFocus",
	1037: "WindowMaximise",
	1038: "WindowMinimise",
	1039: "WindowToggleFrameless",
	1040: "WindowRestore",
	1041: "WindowRuntimeReady",
	1042: "WindowShow",
	1043: "WindowUnFullscreen",
	1044: "WindowUnMaximise",
	1045: "WindowUnMinimise",
	1046: "WindowZoom",
	1047: "WindowZoomIn",
	1048: "WindowZoomOut",
	1049: "WindowZoomReset",
	1050: "ApplicationStartup",
	1051: "SystemThemeChanged",
	1052: "WindowDeleteEvent",
	1053: "WindowDidMove",
	1054: "WindowDidResize",
	1055: "WindowFocusIn",
	1056: "WindowFocusOut",
	1057: "WindowLoadChanged",
	1058: "ApplicationDidBecomeActive",
	1059: "ApplicationDidChangeBackingProperties",
	1060: "ApplicationDidChangeEffectiveAppearance",
	1061: "ApplicationDidChangeIcon",
	1062: "ApplicationDidChangeOcclusionState",
	1063: "ApplicationDidChangeScreenParameters",
	1064: "ApplicationDidChangeStatusBarFrame",
	1065: "ApplicationDidChangeStatusBarOrientation",
	1066: "ApplicationDidChangeTheme",
	1067: "ApplicationDidFinishLaunching",
	1068: "ApplicationDidHide",
	1069: "ApplicationDidResignActive",
	1070: "ApplicationDidUnhide",
	1071: "ApplicationDidUpdate",
	1072: "ApplicationShouldHandleReopen",
	1073: "ApplicationWillBecomeActive",
	1074: "ApplicationWillFinishLaunching",
	1075: "ApplicationWillHide",
	1076: "ApplicationWillResignActive",
	1077: "ApplicationWillTerminate",
	1078: "ApplicationWillUnhide",
	1079: "ApplicationWillUpdate",
	1080: "MenuDidAddItem",
	1081: "MenuDidBeginTracking",
	1082: "MenuDidClose",
	1083: "MenuDidDisplayItem",
	1084: "MenuDidEndTracking",
	1085: "MenuDidHighlightItem",
	1086: "MenuDidOpen",
	1087: "MenuDidPopUp",
	1088: "MenuDidRemoveItem",
	1089: "MenuDidSendAction",
	1090: "MenuDidSendActionToItem",
	1091: "MenuDidUpdate",
	1092: "MenuWillAddItem",
	1093: "MenuWillBeginTracking",
	1094: "MenuWillDisplayItem",
	1095: "MenuWillEndTracking",
	1096: "MenuWillHighlightItem",
	1097: "MenuWillOpen",
	1098: "MenuWillPopUp",
	1099: "MenuWillRemoveItem",
	1100: "MenuWillSendAction",
	1101: "MenuWillSendActionToItem",
	1102: "MenuWillUpdate",
	1103: "WebViewDidCommitNavigation",
	1104: "WebViewDidFinishNavigation",
	1105: "WebViewDidReceiveServerRedirectForProvisionalNavigation",
	1106: "WebViewDidStartProvisionalNavigation",
	1107: "WindowDidBecomeKey",
	1108: "WindowDidBecomeMain",
	1109: "WindowDidBeginSheet",
	1110: "WindowDidChangeAlpha",
	1111: "WindowDidChangeBackingLocation",
	1112: "WindowDidChangeBackingProperties",
	1113: "WindowDidChangeCollectionBehavior",
	1114: "WindowDidChangeEffectiveAppearance",
	1115: "WindowDidChangeOcclusionState",
	1116: "WindowDidChangeOrderingMode",
	1117: "WindowDidChangeScreen",
	1118: "WindowDidChangeScreenParameters",
	1119: "WindowDidChangeScreenProfile",
	1120: "WindowDidChangeScreenSpace",
	1121: "WindowDidChangeScreenSpaceProperties",
	1122: "WindowDidChangeSharingType",
	1123: "WindowDidChangeSpace",
	1124: "WindowDidChangeSpaceOrderingMode",
	1125: "WindowDidChangeTitle",
	1126: "WindowDidChangeToolbar",
	1127: "WindowDidDeminiaturize",
	1128: "WindowDidEndSheet",
	1129: "WindowDidEnterFullScreen",
	1130: "WindowDidEnterVersionBrowser",
	1131: "WindowDidExitFullScreen",
	1132: "WindowDidExitVersionBrowser",
	1133: "WindowDidExpose",
	1134: "WindowDidFocus",
	1135: "WindowDidMiniaturize",
	1136: "WindowDidMove",
	1137: "WindowDidOrderOffScreen",
	1138: "WindowDidOrderOnScreen",
	1139: "WindowDidResignKey",
	1140: "WindowDidResignMain",
	1141: "WindowDidResize",
	1142: "WindowDidUpdate",
	1143: "WindowDidUpdateAlpha",
	1144: "WindowDidUpdateCollectionBehavior",
	1145: "WindowDidUpdateCollectionProperties",
	1146: "WindowDidUpdateShadow",
	1147: "WindowDidUpdateTitle",
	1148: "WindowDidUpdateToolbar",
	1149: "WindowDidZoom",
	1150: "WindowFileDraggingEntered",
	1151: "WindowFileDraggingExited",
	1152: "WindowFileDraggingPerformed",
	1153: "WindowHide",
	1154: "WindowMaximise",
	1155: "WindowUnMaximise",
	1156: "WindowMinimise",
	1157: "WindowUnMinimise",
	1158: "WindowShouldClose",
	1159: "WindowShow",
	1160: "WindowWillBecomeKey",
	1161: "WindowWillBecomeMain",
	1162: "WindowWillBeginSheet",
	1163: "WindowWillChangeOrderingMode",
	1164: "WindowWillClose",
	1165: "WindowWillDeminiaturize",
	1166: "WindowWillEnterFullScreen",
	1167: "WindowWillEnterVersionBrowser",
	1168: "WindowWillExitFullScreen",
	1169: "WindowWillExitVersionBrowser",
	1170: "WindowWillFocus",
	1171: "WindowWillMiniaturize",
	1172: "WindowWillMove",
	1173: "WindowWillOrderOffScreen",
	1174: "WindowWillOrderOnScreen",
	1175: "WindowWillResignMain",
	1176: "WindowWillResize",
	1177: "WindowWillUnfocus",
	1178: "WindowWillUpdate",
	1179: "WindowWillUpdateAlpha",
	1180: "WindowWillUpdateCollectionBehavior",
	1181: "WindowWillUpdateCollectionProperties",
	1182: "WindowWillUpdateShadow",
	1183: "WindowWillUpdateTitle",
	1184: "WindowWillUpdateToolbar",
	1185: "WindowWillUpdateVisibility",
	1186: "WindowWillUseStandardFrame",
	1187: "WindowZoomIn",
	1188: "WindowZoomOut",
	1189: "WindowZoomReset",
	1190: "APMPowerSettingChange",
	1191: "APMPowerStatusChange",
	1192: "APMResumeAutomatic",
	1193: "APMResumeSuspend",
	1194: "APMSuspend",
	1195: "ApplicationStarted",
	1196: "SystemThemeChanged",
	1197: "WebViewNavigationCompleted",
	1198: "WindowActive",
	1199: "WindowBackgroundErase",
	1200: "WindowClickActive",
	1201: "WindowClosing",
	1202: "WindowDidMove",
	1203: "WindowDidResize",
	1204: "WindowDPIChanged",
	1205: "WindowDragDrop",
	1206: "WindowDragEnter",
	1207: "WindowDragLeave",
	1208: "WindowDragOver",
	1209: "WindowEndMove",
	1210: "WindowEndResize",
	1211: "WindowFullscreen",
	1212: "WindowHide",
	1213: "WindowInactive",
	1214: "WindowKeyDown",
	1215: "WindowKeyUp",
	1216: "WindowKillFocus",
	1217: "WindowNonClientHit",
	1218: "WindowNonClientMouseDown",
	1219: "WindowNonClientMouseLeave",
	1220: "WindowNonClientMouseMove",
	1221: "WindowNonClientMouseUp",
	1222: "WindowPaint",
	1223: "WindowRestore",
	1224: "WindowSetFocus",
	1225: "WindowShow",
	1226: "WindowStartMove",
	1227: "WindowStartResize",
	1228: "WindowUnFullscreen",
	1229: "WindowZOrderChanged",
	1230: "WindowMinimise",
	1231: "WindowUnMinimise",
	1232: "WindowMaximise",
	1233: "WindowUnMaximise",
}

